"""
Output generation module for Claude Dictate
Generates output files in various formats (Markdown, PRD, Prompt).
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional


class OutputGenerator:
    """Generates output files in various formats."""

    def __init__(self, output_dir: str = "./outputs"):
        """
        Initialize the output generator.

        Args:
            output_dir: Directory to save output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_filename(self, prefix: str = "dictation", ext: str = "md") -> str:
        """
        Generate a unique filename with timestamp.

        Args:
            prefix: Filename prefix
            ext: File extension

        Returns:
            Generated filename
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"{prefix}_{timestamp}.{ext}"

    def save_markdown(
        self,
        text: str,
        title: str = "",
        filename: str = ""
    ) -> str:
        """
        Save text as a markdown file.

        Args:
            text: Content to save
            title: Document title
            filename: Custom filename (auto-generated if empty)

        Returns:
            Path to the saved file
        """
        if not filename:
            filename = self.generate_filename("dictation", "md")

        filepath = self.output_dir / filename
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        content = f"""# {title or 'Dictation'}

{text}

---
*Generated by Claude Dictate on {timestamp}*
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        return str(filepath)

    def save_prd(
        self,
        text: str,
        title: str = "",
        filename: str = ""
    ) -> str:
        """
        Save text as a PRD (Product Requirements Document) markdown file.

        Args:
            text: Content to save
            title: Document title
            filename: Custom filename (auto-generated if empty)

        Returns:
            Path to the saved file
        """
        if not filename:
            filename = self.generate_filename("prd", "md")

        filepath = self.output_dir / filename
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        content = f"""# {title or 'Product Requirements Document'}

## Overview

{text}

## Goals

<!-- Define the primary objectives -->

-

## User Stories

<!-- Add user stories based on the requirements above -->

- [ ] As a user, I want to...
- [ ] As a developer, I want to...

## Technical Requirements

<!-- Technical implementation details -->

### Architecture

### Dependencies

### Constraints

## Success Criteria

<!-- Define what "done" looks like -->

- [ ] All requirements implemented
- [ ] Tests passing with >80% coverage
- [ ] No linter errors
- [ ] Documentation updated

## Out of Scope

<!-- What is explicitly NOT included -->

## Notes

---
*Generated by Claude Dictate on {timestamp}*
*Compatible with Claude Code and Ralph Wiggum workflow*
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        return str(filepath)

    def save_prompt(
        self,
        text: str,
        title: str = "",
        filename: str = ""
    ) -> str:
        """
        Save text as a prompt file for Claude Code.

        Args:
            text: Content to save
            title: Document title
            filename: Custom filename (auto-generated if empty)

        Returns:
            Path to the saved file
        """
        if not filename:
            filename = self.generate_filename("prompt", "md")

        filepath = self.output_dir / filename
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        content = f"""# {title or 'Claude Code Prompt'}

{text}

---

## Completion Criteria

When this task is fully complete, output: <promise>DONE</promise>

## Process

1. Analyze the requirements above carefully
2. Create a plan before implementing
3. Execute step by step, testing each part
4. Verify the final result matches requirements
5. Document any important decisions made

## Guidelines

- Ask clarifying questions if requirements are ambiguous
- Prefer simple, maintainable solutions
- Include error handling
- Add comments for complex logic
- Follow existing code conventions

---
*Generated by Claude Dictate on {timestamp}*
*Ready for use with Claude Code*
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        return str(filepath)

    def save_ralph_prompt(
        self,
        text: str,
        title: str = "",
        filename: str = ""
    ) -> str:
        """
        Save text as a Ralph Wiggum loop prompt.

        Args:
            text: Content to save
            title: Document title
            filename: Custom filename (auto-generated if empty)

        Returns:
            Path to the saved file
        """
        if not filename:
            filename = self.generate_filename("ralph", "md")

        filepath = self.output_dir / filename
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        content = f"""# {title or 'Ralph Loop Task'}

{text}

---

## Success Criteria

<!-- Claude will iterate until ALL criteria are met -->

- [ ] Primary objective achieved
- [ ] All tests passing
- [ ] No linter/type errors
- [ ] Code is clean and documented

## If Stuck

After multiple iterations without progress:
1. Document what's blocking progress
2. List approaches already attempted
3. Suggest alternative solutions
4. Output <promise>BLOCKED</promise>

## Completion

When ALL success criteria are met, output: <promise>COMPLETE</promise>

---
*Generated by Claude Dictate on {timestamp}*
*Formatted for /ralph-loop usage*

<!-- Usage example:
/ralph-loop "$(cat this_file.md)" --max-iterations 25 --completion-promise "COMPLETE"
-->
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        return str(filepath)

    def save_claude_command(
        self,
        text: str,
        command_name: str = "custom"
    ) -> str:
        """
        Save as a Claude Code custom slash command.

        Args:
            text: Command content
            command_name: Name for the command

        Returns:
            Path to the saved file
        """
        commands_dir = Path.home() / ".claude" / "commands"
        commands_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{command_name.lower().replace(' ', '-')}.md"
        filepath = commands_dir / filename

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(text)

        return str(filepath)

    def get_output_directory(self) -> str:
        """Get the current output directory path."""
        return str(self.output_dir)

    def set_output_directory(self, path: str) -> None:
        """
        Set a new output directory.

        Args:
            path: New directory path
        """
        self.output_dir = Path(path)
        self.output_dir.mkdir(parents=True, exist_ok=True)
